### ISSUE TITLE
An error occurs when using `export.py`

### ISSUE THREAD

**Issue by xiechuanyu** [SensorsINI/ddd20-utils#1]
When I use export.py to generate frame data
**script**
> python ddd20-utils\export.py 1487339175.hdf5

An error occurs.
**error message**
> fuel_level final block: 4.0
high_beam_status final block: 1.0
longitude final block: 1.0
engine_speed final block: 26.0
fuel_consumed_since_restart final block: 23.0
accelerator_pedal_position final block: 26.0
parking_brake_status final block: 5.0
odometer final block: 21.0
torque_at_transmission final block: 26.0
windshield_wiper_status final block: 1.0
latitude final block: 1.0
headlamp_status final block: 1.0
steering_wheel_angle final block: 26.0
transmission_gear_position final block: 1.0
dvs final block: 925.0
vehicle_speed final block: 26.0
ignition_status final block: 5.0
brake_pedal_status final block: 1.0
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "ddd20-utils\export.py", line 103, in <module>
    f_in = HDF5Stream(args.filename, export_data_vi.union({'dvs'}))
  File "D:\jupyter\DDD17\ddd20-utils\view.py", line 73, in __init__
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    self.start()
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    exitcode = _main(fd)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self._popen = self._Popen(self)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    self = reduction.pickle.load(from_parent)
  File "stringsource", line 7, in h5py.h5f.__pyx_unpickle_FileID
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
  File "h5py\_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
    return Popen(process_obj)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
    reduction.dump(process_obj, to_child)
  File "C:\Users\lenovo\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by duguyue100** [comment]
What is your Python version? This project is only working with Python 2 at the moment

**Comment by xiechuanyu** [comment]
？？？
为什么 2020 年还用 python 2 ？

**Comment by duguyue100** [comment]
Because the project was initially written 3 years ago (original author graduated) and many specifics only apply to Python 2 (see README as well).
It only takes you a few minutes to install a Python 2 environment.

**Comment by xiechuanyu** [comment]
Thanks. I apologize for my rudeness.
