### ISSUE TITLE
Error occurs when using `python export.py 1487339175.hdf5`

### ISSUE THREAD

**Issue by xiechuanyu** [SensorsINI/ddd20-utils#3]
OS: `Windows`
python versioin:`2.7`
script: `python export.py 1487339175.hdf5`

> accelerator_pedal_position final block: 26.0
ignition_status final block: 5.0
transmission_gear_position final block: 1.0
parking_brake_status final block: 5.0
headlamp_status final block: 1.0
windshield_wiper_status final block: 1.0
fuel_level final block: 4.0
engine_speed final block: 26.0
fuel_consumed_since_restart final block: 23.0
steering_wheel_angle final block: 26.0
high_beam_status final block: 1.0
torque_at_transmission final block: 26.0
longitude final block: 1.0
odometer final block: 21.0
vehicle_speed final block: 26.0
brake_pedal_status final block: 1.0
latitude final block: 1.0
dvs final block: 925.0
Traceback (most recent call last):
  File "ddd20-utils/export.py", line 103, in <module>
    f_in = HDF5Stream(args.filename, export_data_vi.union({'dvs'}))
  File "D:\jupyter\DDD17\ddd20-utils\view.py", line 73, in __init__
    self.start()
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\site-packages\h5py\_hl\base.py", line 308, in __getnewa
rgs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled
(ddd20) D:\jupyter\DDD17>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\pickle.py", line 1223, in load_build
    setstate(state)
  File "C:\Users\lenovo\Anaconda3\envs\ddd20\lib\multiprocessing\heap.py", line 75, in __setstate__
    assert win32.GetLastError() == win32.ERROR_ALREADY_EXISTS
AssertionError

**Comment by xiechuanyu** [comment]
When I run this script on Ubuntu.
This error dismiss.
But nothing is exported or saved.
> ...
...
...
280.94s done...
280.95s done...
280.96s done...
280.97s done...
280.98s done...
280.99s done...
281.0s done...
[DEBUG] sys_ts/tstop 1487339524.33 1487339524.33
[DEBUG] output done
[DEBUG] waiting for merger
[DEBUG] merger done
[DEBUG] stream joined
[DEBUG] merger joined
Finished.  Wrote 0.0MiB to 1487339175_export.hdf5.

**Comment by xiechuanyu** [comment]
有人吗？我只是想导出 event data 怎么就这么难，原始数据又不知道啥意思

**Comment by tobidelbruck** [comment]
I don't know why the export results in 0MB file, but we know for sure 
that ddd20 only works on linux and with python2.7. I worked for at least 
2 days to try to get it working in python 3 + windows and failed. Best 
is just run it under linux.  Maybe Yuhaung can help with why the file is 
empty for you right now.

**Comment by duguyue100** [comment]
I will close this issue for now as the problem can be dealt with in the other issue #1

**Comment by LarryDong** [comment]
I got the same problem when exporting. Always "Wrote 0.0Mib to xxx_export.hdf5".  
I changed the `datasets.py` file, "import queue" -> "import Queue". Then valid frames can be saved.
