### ISSUE TITLE
Error in view.py script

### ISSUE THREAD

**Issue by albertopolito** [SensorsINI/ddd20-utils#5]
Good morning,
I have an error on running the code view.py :

`(ddd20) [alberto.viale@pc-lse-1854 ddd20-utils]$ python view.py rec1501902136.hdf5
Traceback (most recent call last):
  File "view.py", line 32, in <module>
    from interfaces.caer import DVS_SHAPE, unpack_header, unpack_data
  File "/home/alberto.viale/ddd20-utils/interfaces/__init__.py", line 3, in <module>
    import interfaces.oxc as openxc
  File "/home/alberto.viale/ddd20-utils/interfaces/oxc.py", line 15, in <module>
    from openxc.tools import dump as oxc
  File "/home/alberto.viale/miniconda3/envs/ddd20/lib/python2.7/site-packages/openxc/tools/dump.py", line 14, in <module>
    from .common import device_options, configure_logging, select_device
  File "/home/alberto.viale/miniconda3/envs/ddd20/lib/python2.7/site-packages/openxc/tools/common.py", line 7, in <module>
    from openxc.sources.trace import TraceDataSource
  File "/home/alberto.viale/miniconda3/envs/ddd20/lib/python2.7/site-packages/openxc/sources/__init__.py", line 1, in <module>
    from .base import DataSource, DataSourceError
  File "/home/alberto.viale/miniconda3/envs/ddd20/lib/python2.7/site-packages/openxc/sources/base.py", line 139
    print("LOG: %s" % message, file=log_file)
                                   ^
SyntaxError: invalid syntax
`

Thanks.

**Comment by albertopolito** [comment]
Sorry, I don't install opencv correctly. Now it works.

**Comment by duguyue100** [comment]
Awesome!
